// Standalone env module for FISHBOWLZ

export const ENV = {
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL!,
  SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY!,
  NEYNAR_API_KEY: process.env.NEYNAR_API_KEY!,
  SESSION_SECRET: process.env.SESSION_SECRET!,
  ZAO_OFFICIAL_SIGNER_UUID: process.env.ZAO_OFFICIAL_SIGNER_UUID || '',
  ZAO_OFFICIAL_NEYNAR_API_KEY: process.env.ZAO_OFFICIAL_NEYNAR_API_KEY || '',
  ZAO_OFFICIAL_FID: process.env.ZAO_OFFICIAL_FID || '',
};
